name:                habito-proofs-talk
version:             0.1.0.0
github:              "alexpeits/habito-proofs-talk"
license:             BSD3
author:              "Alex Peitsinis"
maintainer:          "alex.peitsinis@habito.com"
copyright:           "2019 Alex Peitsinis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexpeits/habito-proofs-talk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
